const SYMBOLS = ['☀️','🌙','⭐','❤️','⚡','🔥','🍀','🌈','🚀','🐙','🦋','🍓','🎈','👑','💎','🎵','👻','🧿','🌵','🍕','🐳','🦄','⚓','🍉'];
const POSITIONS = [[50,18,-8],[23,35,12],[76,37,-12],[49,51,7],[25,69,-6],[75,70,9],[50,83,-3]];
const state={mode:'solo',score:0,other:0,time:60,timer:null,match:null,sound:true,turn:1,lastMode:'solo'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();tg.setHeaderColor('#ede8ff');tg.setBackgroundColor('#ede8ff');}
function haptic(type='light'){tg?.HapticFeedback?.impactOccurred(type)}
let audioContext;
function tone(frequency=440,duration=.06,type='sine',volume=.035){if(!state.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator();const gain=audioContext.createGain();oscillator.type=type;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}catch{}}
function clickFeedback(button){button?.classList.add('button-pulse');setTimeout(()=>button?.classList.remove('button-pulse'),260);tone(310,.045,'sine',.025);haptic('light')}
function syncHeader(){['LeftScore','RightScore'].forEach(k=>$('#header'+k).textContent=$('#'+k[0].toLowerCase()+k.slice(1)).textContent);$('#headerTimer').textContent=$('#timer').textContent;$('#headerLeftLabel').textContent=$('#leftLabel').textContent;$('#headerRightLabel').textContent=$('#rightLabel').textContent}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');$('.app').classList.toggle('playing',id==='#gameScreen')}
function sample(arr,n,exclude=[]){return [...arr].filter(x=>!exclude.includes(x)).sort(()=>Math.random()-.5).slice(0,n)}
function makeRound(){const match=sample(SYMBOLS,1)[0];state.match=match;const left=[match,...sample(SYMBOLS,6,[match])].sort(()=>Math.random()-.5);const right=[match,...sample(SYMBOLS,6,[match,...left.filter(x=>x!==match)])].sort(()=>Math.random()-.5);renderCards([left,right])}
function renderCards(cards){const root=$('#cards');root.innerHTML='';cards.forEach(items=>{const card=document.createElement('div');card.className='card';items.forEach((symbol,i)=>{const b=document.createElement('button');b.className='symbol';b.textContent=symbol;b.setAttribute('aria-label',symbol);const [x,y,r]=POSITIONS[i];b.style=`left:calc(${x}% - 27px);top:calc(${y}% - 27px);transform:rotate(${r}deg) scale(${.8+Math.random()*.25})`;b.onclick=()=>pick(b,symbol);card.append(b)});root.append(card)})}
function pick(button,symbol){if(symbol===state.match){button.classList.add('correct');tone(720,.12,'sine',.05);setTimeout(()=>tone(940,.13,'sine',.035),65);haptic('medium');if(state.mode==='solo'){state.score++;$('#leftScore').textContent=state.score}else{if(state.turn===1)state.score++;else state.other++;updateDuel();if(state.score>=7||state.other>=7)return setTimeout(endGame,350);state.turn=state.turn===1?2:1}syncHeader();setTimeout(makeRound,260)}else{button.classList.add('wrong');tone(145,.15,'sawtooth',.035);haptic('heavy');setTimeout(()=>button.classList.remove('wrong'),320);if(state.mode==='solo'&&state.score>0){state.score--;$('#leftScore').textContent=state.score;syncHeader()}}}
function updateDuel(){$('#leftScore').textContent=state.score;$('#rightScore').textContent=state.other;$('#turnBanner').textContent=`Ход игрока ${state.turn===1?2:1}`;syncHeader()}
function startGame(mode){state.mode=state.lastMode=mode;state.score=state.other=0;state.turn=1;clearInterval(state.timer);show('#gameScreen');if(mode==='solo'){$('#leftLabel').textContent='ОЧКИ';$('#rightLabel').textContent='РЕКОРД';$('#rightScore').textContent=localStorage.getItem('dobble-best')||0;state.time=60;$('#turnBanner').textContent='Найди общий символ';state.timer=setInterval(()=>{state.time--;drawTime();if(state.time<=0)endGame()},1000)}else{$('#leftLabel').textContent='ИГРОК 1';$('#rightLabel').textContent='ИГРОК 2';$('#rightScore').textContent='0';$('#turnBanner').textContent='Ход игрока 1';state.time=0}$('#leftScore').textContent='0';drawTime();syncHeader();makeRound()}
function drawTime(){if(state.mode!=='solo')$('#timer').textContent='до 7';else{const minutes=Math.floor(state.time/60);const seconds=state.time%60;$('#timer').textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}syncHeader()}
function endGame(){clearInterval(state.timer);if(state.mode==='solo'){const best=Math.max(state.score,+(localStorage.getItem('dobble-best')||0));localStorage.setItem('dobble-best',best);$('#resultTitle').textContent=state.score===best&&state.score>0?'Новый рекорд!':'Отличная игра!';$('#resultText').textContent='Совпадений найдено';$('#resultScore').textContent=state.score;$('#resultIcon').textContent='★'}else{const winner=state.score>state.other?1:2;$('#resultTitle').textContent=`Игрок ${winner} победил!`;$('#resultText').textContent=`Финальный счёт ${state.score} : ${state.other}`;$('#resultScore').textContent='🏆';$('#resultIcon').textContent=winner===1?'1':'2'}show('#resultScreen')}
$$('[data-mode]').forEach(b=>b.onclick=()=>{clickFeedback(b);setTimeout(()=>startGame(b.dataset.mode),110)});$('#exitButton').onclick=e=>{clickFeedback(e.currentTarget);endGame()};$('#againButton').onclick=e=>{clickFeedback(e.currentTarget);setTimeout(()=>startGame(state.lastMode),100)};$('#homeButton').onclick=e=>{clickFeedback(e.currentTarget);setTimeout(()=>show('#homeScreen'),100)};$('#rulesButton').onclick=e=>{clickFeedback(e.currentTarget);$('#rulesDialog').showModal()};$('#closeRules').onclick=e=>{clickFeedback(e.currentTarget);$('#rulesDialog').close()};$('#soundButton').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♪':'×';e.currentTarget.setAttribute('aria-label',state.sound?'Звук включён':'Звук выключен');if(state.sound)tone(520,.08)};
